### ISSUE TITLE
NameError in localcider.backend.sequence.py

### ISSUE THREAD

**Issue by jcbollinger** [Pappulab/localCIDER#9]
Since commit 6f8c372, all 51 tests fail with the same `NameError` when run via `python setup.py test`.  For example:

```
======================================================================
ERROR: test_linear_vectors (localcider.tests.test_sequence.TestSequenceFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jbolling/work/localCIDER/localcider/tests/test_sequence.py", line 61, in setUp
    self.SO_60 = sequence.Sequence('MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGP')
  File "/home/jbolling/work/localCIDER/localcider/backend/sequence.py", line 133, in __init__
    self.compFileName = compFileName
NameError: global name 'compFileName' is not defined
```

**Comment by jcbollinger** [comment]
Furthermore, if this issue is worked around by adding a suitably named parameter to `localcider.backend.sequence.Sequence.__init__()` then the relevant tests fail with a `KeyError` instead:

```
======================================================================
ERROR: test_pathological_sequences (localcider.tests.test_sequenceParameters.TestSequenceParametersFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jbolling/work/localCIDER/localcider/tests/test_sequenceParameters.py", line 551, in test_pathological_sequences
    a.get_kappa(), 12))
  File "/home/jbolling/work/localCIDER/localcider/sequenceParameters.py", line 263, in get_kappa
    return self.SeqObj.kappa()
  File "/home/jbolling/work/localCIDER/localcider/backend/sequence.py", line 433, in kappa
    if self.deltaMax() == 0:
  File "/home/jbolling/work/localCIDER/localcider/backend/sequence.py", line 1267, in deltaMax
    nseq = Sequence(setupSequence)
  File "/home/jbolling/work/localCIDER/localcider/backend/sequence.py", line 138, in __init__
    AADICT[i] += 1
KeyError: '+'
```

**Comment by jcbollinger** [comment]
Also, some tabs were introduced into `localcider.backend.sequence.py`.  These seem not to bother Python 2.7, but from at least Python 3.6, indentation of any given construct needs to be consistent with respect to tabs and spaces.
